# Generated by Django 5.1.1 on 2024-11-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text='A book cover per post', null=True, upload_to=''),
        ),
    ]
